name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build HTML and PDF
        uses: ./.github/actions/build-docs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: _build/html
          name: docs
          overwrite: true
